name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 1 * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: vlingo/xoom-platform/.github/workflows/reusable/build.yml@master
    secrets: inherit
